---

- include: vpc.yml

- include: vpc_routes.yml
  when: aws_manage_vpc_routes is defined

- include: groups.yml

- include: aws_info.yml
  when: aws_manage_vpc_write_info

- include: rds_subnet_group.yml
  when: aws_manage_rds_subnet_group is defined 