---

- name: vpc | Check vpc definition file exists
  stat: 
    path="{{ aws_manage_vpc_def_path }}"
  register: vpc_definition_file
  when: aws_manage_vpc_def_path is defined

- name:  vpc | Include AWS definition file
  include_vars: "{{ aws_manage_vpc_def_path }}"
  when: aws_manage_vpc_def_path is defined and vpc_definition_file.stat.exists

- name: vpc | Set the VPC
  ec2_vpc:
  args:
    "{{ item }}"
  with_items: aws_manage_vpc
  register: vpc
